# =============================================================================
# File: .pre-commit-config.yaml
# Purpose:
#   Define pre-commit hooks for formatting, linting, security checks.
#
# Hooks (examples):
#   - ruff, black, isort
#   - sqlfluff for /sql
#   - trailing-whitespace, end-of-file-fixer
#
# Notes:
#   - Install with: pre-commit install
# =============================================================================

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.7,<3.0

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.5
    hooks:
      - id: sqlfluff-lint
        args: [--dialect=ansi]
        files: ^sql/.*\.sql$
      - id: sqlfluff-fix
        args: [--dialect=ansi]
        files: ^sql/.*\.sql$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
