"""noop plumbing check

Revision ID: b01edbc4c937
Revises: ddc1645c7dfa
Create Date: 2025-10-06 09:57:38.556929+00:00
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b01edbc4c937"
down_revision: str | None = "ddc1645c7dfa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
