"""Test

Revision ID: 460e2199c8df
Revises: b01edbc4c937
Create Date: 2025-10-08 02:03:09.532521+00:00
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "460e2199c8df"
down_revision: str | None = "b01edbc4c937"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
